### ISSUE TITLE
Intermittent "- HTTP:Could not connect to host trace: #0 [internal function]: SoapClient->__doRequest()"

### ISSUE THREAD

**Issue by drimondi1** [BingAds/BingAds-PHP-SDK#151]
we are facing  an intermitting connection error "- HTTP:Could not connect to host
trace: #0 [internal function]: SoapClient->__doRequest()
"  while using the SDK please see more details below in logs  (GetEstimatase API ):

```shell
[2021-05-21 08:32:44] prod.INFO: M.R3_BAY.-CWNHEZV5771ZoyYjOIlSaEQ0IhZKeOf7OTnNTXreEOY0jXeaTWXuy072F5rEIpFWLtcb323uSoSFfgZSEx0fuDFbCd8zVWlV!k6mU3RvgqAXmTgvw!ABq6N1KVSiHZSG6NcSuUBWZ2XrYW2fzhQbxnSwbCXBjbWAQQYq7XrUbiQHN9lIy0c9gYRYew9xbCUfGTS1TUgPpf3olKa48t6W0oAH9MoqfeEXfq!Fue2rOahdvq7e6cOfA6s!u0cryIxKFmO5b8x*RPaVcnUgbZYMfCOgyFm1!YryGh5OOmPvr6VPRM91EsBcWYv9!En1N3gx*hICoQQW4iLCwsOLZqJzmG7wrYzb09P6IlKMU8VXl8m2  

[2021-05-21 08:32:46] prod.INFO: M.R3_BAY.-CbOZ59!BPhcvL0V5N77WCbjy3AJqLM6Yk3Pt3DA!rg9xAekZuquVcGx9VNonyE5yrgu25X1G*TNv2azLoK8gYDnkz44Kp8oqn8jgpq7*TW2uwSL2nIwGl8CONK79z6Ekpkz86SF48*wAaypPNtLbd9KfHuCH2MxFN*WNsISMnAY6s*SJ!bD1eMvQMQwiinjHJQndxUhEPyB0kc7rVw!U1SanUCzM3hO8PN7SJtKTuYMirvXm6e0FIbGRHHvMJZp5cIwUr!wy4qw5cxPIWNl*E7fAGjBmar*9WXusr3gqaNazpZAge2Ms03ffwVzimUVLTIHFarDav356g0xnXSxo9tyDt7Kq*FPMfGFb*eNxzgUs  

[2021-05-21 08:32:47] prod.INFO: M.R3_BAY.-CaTN3YUlqiaJCqEDWT*FkLpEtjs0Y2i!FhjzfNXOb2sxbc!zlsZaWYQi0SOd7Q1vRRl4ScDzgQBjlwQODGdH01oU*6t9wi*tO7HiAOxwrGJJ0PfxefT*OR0LGhVvxtCCaLc00W9FX*9npuapwQQF8BEhxHY*ttzt*laG!35*mzRhRvvDeFjotySdfSdKCU2V8k*iOZMYW*NX7JEB9fr2pae5ktX8G1RgAh0ROevQCNu3CPJdDYI71!XsaJKV1ghd7sldxBsb0WQi9agGN2Pn8QOJd!nmmeA1HwgA6Jw11GXjg84K4uqhhOlMn7Wbktmf1G!kc2s78rq3kO4rzS1HhRgVDiG2EX6KxV9u1D2URqmg  

[2021-05-21 08:33:48] prod.ERROR: /home/username/GIT/productname/application/app-bing/app-shared/Utilities/BingInterface.php:296 - HTTP:Could not connect to host
trace: #0 [internal function]: SoapClient->__doRequest()
#1 /home/username/GIT/productname/application/app-bing/app-shared/Utilities/BingInterface.php(296): SoapClient->__call()
#2 /home/username/GIT/productname/application/app-bing/app-shared/Utilities/BingInterface.php(278): company\Utilities\BingInterface->getKeywordEstimate()
#3 /home/username/GIT/productname/application/app-bing/app-shared/Utilities/BingInterface.php(254): company\Utilities\BingInterface->getKeywordEstimates()
#4 /home/username/GIT/productname/application/app-bing/app/Console/Commands/testBing.php(48): company\Utilities\BingInterface->getKeywords()
#5 /home/username/GIT/productname/application/app-bing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\testBing->handle()
#6 /home/username/GIT/productname/application/app-bing/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#7 /home/username/GIT/productname/application/app-bing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#8 /home/username/GIT/productname/application/app-bing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#9 /home/username/GIT/productname/application/app-bing/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call()
#10 /home/username/GIT/productname/application/app-bing/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call()
#11 /home/username/GIT/productname/application/app-bing/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#12 /home/username/GIT/productname/application/app-bing/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#13 /home/username/GIT/productname/application/app-bing/vendor/symfony/console/Application.php(971): Illuminate\Console\Command->run()
#14 /home/username/GIT/productname/application/app-bing/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#15 /home/username/GIT/productname/application/app-bing/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#16 /home/username/GIT/productname/application/app-bing/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#17 /home/username/GIT/productname/application/app-bing/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#18 /home/username/GIT/productname/application/app-bing/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#19 {main}  

[2021-05-21 08:33:49] prod.INFO: M.R3_BAY.-CTevDKV50E4OuDWy5eQC0EqwpDco*MeFeab9OsUw8s8nxd*d8WXn0t*veDvCt!UeUcp6ELEUcZJ14ttQdBZFkBQosm!goQ!G*mV2E*XbDAeCH17uyLY*myBbsuyz5lslHqp29zmguQySmJIQFxEKN*KAPjeRyLDzEvm2yx*PLX4GFA5p0Lg2YqCBphKESsX!VfjQq3S0IY5rMwEBYuXhjAx9fDLZ9uCVdbjYekhApVSHXvkCCzd2TkeD9TJO8*xIvcZqQPtz4HynjVM1K*j022CFNdWX74jGAw9A2Mbi*d8Xe1MhelP4jHrCM6G5DAB6ep!O4GNmwK3npbMTLueN5UvzslSg49hbbaIZXs8uUClM  

[2021-05-21 08:33:50] prod.INFO: M.R3_BAY.-CRoFoBzhICNHByLq0T9YQXzW8v!EOc46!16!nLH0ToC9edfbiPU*Wo0Z39dFWSwgNIZ*p4jqqK!Px8KMJRI97CZzi1rbTu2nLHYYbXApY5iu1msnRUTWt9!qcukWutPdDsymEUA5qgHrFJHV9fKpIw9WJZnlFVXkt4yq!LIWoeJixa6EmoRMjXq8tVg2IeLngC72N6hjFKvZT!kbGjbWxaT5nEUlxGOwKdDxdOI7wn*DKwAAWV6Gpbv8aWd0dhnJSIGwEq6MltDBqL*6s2LtuWimmCTCE4Ub43*X43!XkyYMRrnJ2R5kgpBokBwgplHtOpt3eXSrxcaz4oXdzcYmEC9Uwi6A!!ZB4HvserYdLz7b  

[2021-05-21 08:33:51] prod.INFO: M.R3_BAY.-CUt5G2tLap65Qkx6EUt*9ZBcdOmHgkGThSOtvBuFANQ*KBKwlE2eM5M*!acogL4e7yrvhwd!tzjMx96WUERZUV4vocOmwsm4OUzAIzNPCABHWjaR1nzGwTLNrFX075QKMrk542O8OPsl6R12nSNyzbXMy*4QoFKgYUjhKqn!!rY9s3QQyidubAnN2EZaV7LbQHYUxl3JgkGw*nHo5Nq4KZ8tONoyoULuIlus*NgW2qG*4J5aUccpV0KjyZkatoIv3N!MAOp0OVLTdyfB71u1Dws*fgkJJhVFIqFPNpzOFG7imFpIEwURSzZ!U*vIMWXhr!AIl8o5ruzLiwuHXp9SNoIJOJBVO1inv89PPUhXaJm6  


```

**Comment by drimondi1** [comment]
Any news ? can you support us on this, we are still facing this problem .
Thanks

**Comment by stucchi** [comment]
Hey there, is there any news on this ? I am having the same issue and I'd like to understand if it's somthing known, and hopefully there is a workaround solution, or an ETA for a fix.

**Comment by lezhnev74** [comment]
We face this issue too. Just a heads up here.
